### ISSUE TITLE
Data limite e paginação 

### ISSUE THREAD

**Issue by TheyCallMeErick** [fix-si/teste-tecnico-quotes-selenium#1]
Tenho duas dúvidas.

1. Qual a data limite para realizar o teste técnico?
2. Após uma breve olhada na página que é para se fazer a raspagem de dados vi que é possível paginar as frases, será necessário isso ou apenas as da página inicial já são suficiente?

**Comment by luanascardua** [comment]
devem ser coletadas todas as citações, de todas as páginas
